spring.application.name=jobhunter

#config database
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/jobhunter
spring.datasource.username=admin
spring.datasource.password=phuc2003@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true


###
# config jwt
huuphuc.jwt.base64-secret= vEaPr88xPVXmczXSA1SZr763wN//kaxV+2HYv0ioB9gJjd4noR3LIU4BvVuEu2fK
9pkK2n+QDspVHDeqeQJ4EQ==

huuphuc.jwt.token-validty-in-seconds=86400

#
###